import { useEffect,useRef,useState } from 'react';
import { Check,Copy,KeyRound,Plus,RefreshCw,ShieldAlert,Trash2 } from 'lucide-react';
import api from '../lib/api';
import PageHeader from '../components/PageHeader';
import { useUi } from '../state/ui-store';
import useStagger from '../hooks/useStagger';
import useModalEnter from '../hooks/useModalEnter';

export default function ApiKeysPage(){
  const {confirm,toast}=useUi();
  const [clients,setClients]=useState([]);const [name,setName]=useState('Production');const [secret,setSecret]=useState(null);const [copied,setCopied]=useState('');
  const [loading,setLoading]=useState(true);const [creating,setCreating]=useState(false);const [busyId,setBusyId]=useState('');
  const rootRef=useRef(null);const secretRef=useRef(null);
  const load=()=>api.get('/clients').then(({data})=>setClients(data.clients)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  useStagger(rootRef, '.client-list article', { dependency: clients.length });
  useModalEnter(secretRef, '.credential-modal', Boolean(secret));
  const create=async()=>{setCreating(true);try{const {data}=await api.post('/clients',{name});setSecret(data.client);await load()}catch(err){toast(err.response?.data?.message||'Could not create credentials','error')}finally{setCreating(false)}};
  const rotate=async client=>{if(!await confirm({title:'Rotate App Secret?',message:`The previous secret for ${client.name} will stop working immediately.`,confirmLabel:'Rotate secret',tone:'danger'}))return;setBusyId(client.id);try{const {data}=await api.post(`/clients/${client.id}/rotate`);setSecret({...client,...data.client});toast('App Secret rotated');await load()}catch(err){toast(err.response?.data?.message||'Could not rotate secret','error')}finally{setBusyId('')}};
  const revoke=async client=>{if(!await confirm({title:'Revoke credentials?',message:`${client.name} will immediately lose API access.`,confirmLabel:'Revoke',tone:'danger'}))return;setBusyId(client.id);try{await api.post(`/clients/${client.id}/revoke`);toast('App credentials revoked','info');await load()}catch(err){toast(err.response?.data?.message||'Could not revoke credentials','error')}finally{setBusyId('')}};
  const copy=async(value,type)=>{await navigator.clipboard.writeText(value);setCopied(type);toast(type==='secret'?'App Secret copied securely':'App ID copied');setTimeout(()=>setCopied(''),1800)};
  const activeCount=clients.filter(client=>client.active).length;
  return <div ref={rootRef}><PageHeader eyebrow="API setup" title="App credentials" description="Issue, rotate, and revoke OAuth credentials for server-to-server integrations." action={<div className="credential-limit"><span>{activeCount}/5 active</span><button className="primary-button compact" onClick={create} disabled={activeCount>=5||creating}>{creating?<RefreshCw className="spin"/>:<Plus/>}{creating?'Creating…':'Create credentials'}</button></div>}/>
    {secret&&<div className="modal-backdrop" ref={secretRef}><section className="secret-vault credential-modal"><div className="vault-icon"><ShieldAlert/></div><div className="vault-copy"><p className="eyebrow">One-time secret</p><h3>{secret.name||'Application'} credentials created</h3><p>This is the only time the App Secret will be available. Store it in your backend secret manager. Never put it in frontend code.</p><div className="vault-fields"><div><small>App ID</small><code>{secret.appId}</code><button onClick={()=>copy(secret.appId,'id')}>{copied==='id'?<Check/>:<Copy/>}<span>{copied==='id'?'Copied':'Copy ID'}</span></button></div><div className="secret-field"><small>App Secret</small><code>••••••••••••••••••••••••••••••••</code><button className="copy-secret-button" onClick={()=>copy(secret.appSecret,'secret')}>{copied==='secret'?<Check/>:<Copy/>}<span>{copied==='secret'?'Copied':'Copy secret'}</span></button></div></div></div><button className="vault-dismiss" onClick={()=>setSecret(null)}>I saved it safely</button></section></div>}
    <section className="panel"><div className="panel-heading"><div><h3>OAuth applications</h3><p>Use a separate credential pair for each integration.</p></div><label className="inline-field">New credential name<input value={name} onChange={e=>setName(e.target.value)}/></label></div><div className="client-list">{loading?<div className="empty-state"><RefreshCw className="spin"/><p>Loading credentials…</p></div>:clients.length?clients.map(client=><article className={!client.active?'revoked':''} key={client.id}><div className="client-icon"><KeyRound/></div><div><strong>{client.name}</strong><code>{client.appId}</code></div><span className={`status ${client.active?'status-active':'status-expired'}`}><i/>{client.active?'Active':'Revoked'}</span><small>{client.lastUsedAt?`Last used ${new Date(client.lastUsedAt).toLocaleString()}`:'Never used'}</small><div className="credential-actions">{client.active&&<button onClick={()=>rotate(client)} disabled={busyId===client.id}>{busyId===client.id?<RefreshCw className="spin"/>:<RefreshCw/>}Rotate</button>}<button className="danger-text" onClick={()=>revoke(client)} disabled={!client.active||busyId===client.id}><Trash2/>Revoke</button></div></article>):<div className="empty-state"><KeyRound/><h4>No app credentials</h4><p>Create a credential pair to use the payment API.</p></div>}</div></section>
  </div>;
}
