import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, Building2, CheckCircle2, Eye, EyeOff, Info, Link2, MoreVertical, RefreshCw, ShieldCheck, Trash2, Unplug, X } from 'lucide-react';
import api from '../lib/api';
import PageHeader from '../components/PageHeader';
import { useUi } from '../state/ui-store';
import useStagger from '../hooks/useStagger';
import useModalEnter from '../hooks/useModalEnter';

export default function ConnectPage() {
  const {confirm,toast}=useUi();
  const [connections,setConnections]=useState([]); const [show,setShow]=useState(false); const [modal,setModal]=useState(null);
  const [form,setForm]=useState({mobile:'',token:'',label:''}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(null);
  const rootRef=useRef(null);
  const load=()=>api.get('/connections').then(({data})=>setConnections(data.connections)); useEffect(()=>{load()},[]);
  useStagger(rootRef, '.merchant-card', { dependency: connections.length });
  const connect=async event=>{event.preventDefault();setBusy(true);setMessage(null);try{await api.post('/connections/bharatpe',form);setForm({mobile:'',token:'',label:''});setMessage({type:'success',text:'BharatPe merchant, mobile number and QR verified successfully.'});load()}catch(err){setMessage({type:'error',text:err.response?.data?.message||'Connection failed. Check the token and registered mobile number.'})}finally{setBusy(false)}};
  const deactivate=async item=>{if(!await confirm({title:'Deactivate connection?',message:`${item.legalBusinessName||'This merchant'} will stop verifying pending payments.`,confirmLabel:'Deactivate',tone:'danger'}))return;try{await api.post(`/connections/${item.id}/deactivate`);toast('Merchant connection deactivated','info');load()}catch(err){toast(err.response?.data?.message||'Could not deactivate connection','error')}};
  const remove=async item=>{if(!await confirm({title:'Delete connection?',message:'This permanently removes the unused merchant connection.',confirmLabel:'Delete',tone:'danger'}))return;try{await api.delete(`/connections/${item.id}`);toast('Merchant connection deleted');load()}catch(err){toast(err.response?.data?.message||'Could not delete connection','error')}};
  const refresh=async item=>{try{await api.post(`/connections/${item.id}/refresh-details`);toast('Settlement and account details refreshed');load()}catch(err){toast(err.response?.data?.message||'Could not refresh merchant details','error')}};
  return <div ref={rootRef}>
    <PageHeader eyebrow="Gateway setup" title="Connect BharatPe Business" description="Verify the registered mobile number, securely import the merchant QR, and activate live payment verification." action={<div className="header-actions"><button className="risk-button" onClick={()=>setModal('risks')}><AlertTriangle/>Important limitations</button><button className="info-button" onClick={()=>setModal('guide')}><Info/>How connection works</button></div>}/>
    <form className="panel form-panel connect-form" onSubmit={connect}><div className="panel-heading"><div><h3>Add business account</h3><p>Use a current token from your own BharatPe Business session.</p></div><div className="provider-pill"><span>B</span>BharatPe Business</div></div><div className="connection-form-grid"><label>Connection label<input placeholder="Main counter" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label>Registered mobile<input required inputMode="numeric" placeholder="10-digit BharatPe mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})}/></label><label>BharatPe token<div className="input-action"><input required type={show?'text':'password'} placeholder="Paste token securely" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/><button aria-label={show?'Hide token':'Show token'} type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label></div><div className="connect-form-footer"><div className="privacy-box"><ShieldCheck/><p><strong>Encrypted at rest</strong><span>The token is never returned to the browser.</span></p></div><button className="primary-button" disabled={busy}>{busy?<><RefreshCw className="spin"/>Verifying merchant…</>:<><Link2/>Connect and verify</>}</button></div>{message&&<div className={`alert ${message.type}`}>{message.text}</div>}</form>
    <section className="connections-section"><div className="section-title"><div><h3>Business connections</h3><p>Only one active connection is allowed for each registered mobile number.</p></div><span>{connections.filter(c=>c.status==='ACTIVE').length} active</span></div><div className="merchant-grid">{connections.length?connections.map(item=><article className={`merchant-card ${item.status.toLowerCase()}`} key={item.id}><div className="merchant-card-top"><div className="merchant-brand"><span>{(item.legalBusinessName||'B')[0]}</span><div><small>{item.provider}</small><strong>{item.legalBusinessName||item.label||'BharatPe merchant'}</strong></div></div><button className="more-button" aria-label="Details" onClick={()=>setModal(item)}><MoreVertical/></button></div><div className="merchant-upi"><span>UPI ID</span><strong>{item.upiId||'Not available'}</strong></div><div className="merchant-facts"><div><small>Status</small><strong className={`connection-status ${item.status.toLowerCase()}`}><i/>{item.status}</strong></div><div><small>Settlement</small><strong className={item.autoSettlement?'settlement-on':''}>{item.autoSettlement?'Automatic':'Manual'}</strong></div><div><small>Bank</small><strong>{item.bankName||'—'}</strong></div></div><div className="merchant-card-footer"><button onClick={()=>setModal(item)}><Building2/>View details</button><button onClick={()=>refresh(item)}><RefreshCw/>Refresh</button>{item.status==='ACTIVE'&&<button className="danger-text" onClick={()=>deactivate(item)}><Unplug/>Deactivate</button>}{item.status!=='ACTIVE'&&<button className="danger-text" onClick={()=>remove(item)}><Trash2/>Delete</button>}</div>{item.isDefault&&<span className="default-ribbon">Default</span>}</article>):<div className="empty-state panel"><CheckCircle2/><h4>No connection yet</h4><p>Add and verify your BharatPe Business account above.</p></div>}</div></section>
    {modal&&<Modal onClose={()=>setModal(null)}>{modal==='guide'?<ConnectionGuide/>:modal==='risks'?<ConnectionRisks/>:<MerchantDetails item={modal}/>}</Modal>}
  </div>;
}

function Modal({children,onClose}){
  const ref=useRef(null);
  useModalEnter(ref,'.modal-card');
  return <div className="modal-backdrop" ref={ref} onMouseDown={onClose}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X/></button>{children}</div></div>;
}
function ConnectionGuide(){const steps=[['01','Merchant verification','We fetch the merchant identity and Merchant ID.'],['02','Mobile validation','The entered number must match BharatPe’s merchant response.'],['03','QR import','We download and decode the official merchant QR.'],['04','Live verification','Verification runs while checkout is active, plus a 30-minute reconciliation.']];return <><p className="eyebrow accent">Connection sequence</p><h2>What happens next</h2><div className="modal-steps">{steps.map(([n,t,d])=><div key={n}><span>{n}</span><p><strong>{t}</strong><small>{d}</small></p></div>)}</div><div className="modal-note"><Info/>Use only a token belonging to your own BharatPe Business account.</div></>}
function ConnectionRisks(){return <><p className="eyebrow danger">Before connecting</p><h2>Merchant connection rules</h2><div className="risk-list"><p><AlertTriangle/><span><strong>One active account per mobile</strong>A registered mobile number cannot have multiple active BharatPe connections.</span></p><p><ShieldCheck/><span><strong>Use only your own account</strong>Tokens grant access to merchant information and transaction verification.</span></p><p><RefreshCw/><span><strong>Tokens can expire</strong>Refresh the connection when BharatPe invalidates the saved session token.</span></p><p><Info/><span><strong>Provider API dependency</strong>Verification depends on BharatPe’s private API availability and response format.</span></p></div></>}
function MerchantDetails({item}){return <><p className="eyebrow accent">Verified merchant</p><h2>{item.legalBusinessName||'BharatPe merchant'}</h2><div className={`settlement-highlight ${item.autoSettlement?'enabled':''}`}><div><small>Auto settlement</small><strong>{item.autoSettlement?'Enabled':'Not enabled'}</strong></div>{item.autoSettlement?<CheckCircle2/>:<AlertTriangle/>}</div><dl className="detail-list"><div><dt>Business name</dt><dd>{item.legalBusinessName||'—'}</dd></div><div><dt>Merchant name</dt><dd>{item.merchantName||'—'}</dd></div><div><dt>Business category</dt><dd>{item.category||'—'}</dd></div><div><dt>Sub-category</dt><dd>{item.subCategory||'—'}</dd></div><div><dt>Beneficiary</dt><dd>{item.beneficiaryName||'—'}</dd></div><div><dt>IFSC</dt><dd>{item.ifsc||'—'}</dd></div><div><dt>Registered mobile</dt><dd>••••••{item.mobile?.slice(-4)}</dd></div><div><dt>Merchant ID</dt><dd>{item.merchantId}</dd></div></dl></>}
